/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

public interface MettelFOObjectFactory{

    final MettelFOObjectFactory DEFAULT = new MettelFODefaultObjectFactory();

    MettelFOReplacement getReplacement(MettelFOReplacement r);

    MettelFOSubstitution getSubstitution(MettelFOSubstitution s);

    MettelFOTrueFormula createTrueFormula();    

    MettelFOFalseFormula createFalseFormula();    

    MettelFONegationFormula createNegationFormula(MettelFOFormula e0);    

    MettelFOConjunctionFormula createConjunctionFormula(MettelFOFormula e0, MettelFOFormula e1);    

    MettelFODisjunctionFormula createDisjunctionFormula(MettelFOFormula e0, MettelFOFormula e1);    

    MettelFOImplicationFormula createImplicationFormula(MettelFOFormula e0, MettelFOFormula e1);    

    MettelFOFormulaEquivalenceFormula createFormulaEquivalenceFormula(MettelFOFormula e0, MettelFOFormula e1);    

    MettelFOFormulaVariable createFormulaVariable(String name);

}
