/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

import mettel.core.MettelExpression;

public class MettelFOFalseFormula extends MettelFOAbstractExpression implements MettelFOFormula{

    static final int PRIORITY = 2;
    private final int LENGTH;

    public MettelFOFalseFormula(MettelFOObjectFactory f){
        super(f);
        int l = 1;
        LENGTH = l;
    }

    int sortId(){ return SORTID; }

    int priority(){ return PRIORITY; }

    public int length(){ return LENGTH; }

    public MettelFOSubstitution match(MettelFOExpression e){
        MettelFOSubstitution s = new MettelFOTreeSubstitution();
        if(match(e,s)){
            return factory.getSubstitution(s);
        }else{ return null; }
    }

    public boolean match(MettelFOExpression e, MettelFOSubstitution s){
        if(!(e instanceof MettelFOFalseFormula)){ return false;}
        return true;
    }

    public MettelFOExpression substitute(MettelFOSubstitution s){
        return this;

    }

    public MettelFOExpression rewrite(MettelFOReplacement s){
        MettelFOExpression e = s.getFormula(this);
        if(e != null){ return e; }
        return this;
    }

    private int hashCode = 0;
    public int hashCode(){
        if(hashCode == 0){
            hashCode = 31*SORTID + PRIORITY;
        }
        return hashCode;
    }

    public boolean equals(Object o){
        if(o == this){ return true; }
        if(!(o instanceof MettelFOFalseFormula)){ return false; }
        return true;
    }

    public int compareTo(MettelExpression e){
        if(e == this){ return 0; }
        if(!(e instanceof MettelFOFormula)){ return SORTID - ((MettelFOAbstractExpression)e).sortId(); }
        if(e instanceof MettelFOFormulaVariable){ return 1; }
        if(!(e instanceof MettelFOFalseFormula)){ return PRIORITY - ((MettelFOAbstractExpression)e).priority(); }
        return 0;
    }

    private String str = null;
    public String toString(){
        if(str == null){
            StringBuilder b = new StringBuilder();
            b.append('(');
            b.append(' ');
            b.append("false");
            b.append(' ');
            b.append(')');
            str = b.toString();
        }
        return str;
    }
}
