/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

public interface MettelFOFormula extends MettelFOExpression{

    final int SORTID = 1;
}
