/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

import java.util.Map;

import mettel.core.tableau.MettelSubstitution;
public interface MettelFOSubstitution extends MettelSubstitution{

    MettelFOFormula getFormula(MettelFOFormulaVariable e);

    Map<MettelFOFormulaVariable, MettelFOFormula> formulaMap();

    boolean append(MettelFOFormulaVariable e0, MettelFOFormula e1);

}
