/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

import java.util.Set;

import mettel.core.tableau.MettelReplacement;

public interface MettelFOReplacement extends MettelReplacement{

    MettelFOFormula getFormula(MettelFOFormula e);

    Set<MettelFOFormula> formulaKeys();

    boolean append(MettelFOFormula e0, MettelFOFormula e1);

    boolean append(MettelFOReplacement r);

}
