/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package mettel.fo;

abstract class MettelFOAbstractVariable extends MettelFOAbstractExpression implements MettelFOVariable{

    String name = null;

    public String name(){
        return name;
    }

    public MettelFOAbstractVariable(String name, MettelFOObjectFactory factory){
        super(factory);
        this.name = name;
    }

    public String toString(){
        return name;
    }
    int priority(){
        return -1;
    }
}
