/**
 * This file is part of MetTeL.
 *
 * MetTeL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MetTeL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MetTeL.  If not, see <http://www.gnu.org/licenses/>.
 */
package mettel.generator.java;

import java.util.ArrayList;
import java.util.Hashtable;

/**
 * @author alijevt1
 *
 */
public class MettelRandomExpressionGeneratorPropertiesFile extends MettelFile implements MettelRandomExpressionDefaultPropertiesValues {
	// perhaps rename
	private Hashtable<String,ArrayList<String>> signatures = new Hashtable<String,ArrayList<String>>();
	
	//TODO make sure it creates properties directory to do that probably needs new class
	// for creating ordinary files (not extending MettelJavaFile)
	public MettelRandomExpressionGeneratorPropertiesFile(String prefix, MettelJavaPackage pack) {
		super(prefix + "RandomExpressionGenerator.properties", null, pack,
				new String[]{
				"# This file is generated by MetTeL v2",
				"# which is designed and implemented",
				"# by Dmitry Tishkovsky."
				});
	}
	
	//TODO perhaps rename also repeating code
	void appendSignature(String type) {
		ArrayList<String> ss = signatures.get(type);
		if(ss == null){
			ss = new ArrayList<String>();
			signatures.put(type, ss);
		}
	}
	
	void appendSignature(String type, String name) {
		ArrayList<String> ss = signatures.get(type);
		if(ss == null){
			ss = new ArrayList<String>();
			signatures.put(type, ss);
		}
		ss.add(name);
	}
	
	public void generateBody() {
//TODO
//		appendLine(MettelRandomExpressionDefaultPropertiesNames.METTEL_VERSION + " = " + METTEL_VERSION_VALUE);
//		appendLine(MettelRandomExpressionDefaultPropertiesNames.SYNTAX + " = " + SYNTAX_PATH);
		for(String type:signatures.keySet()){
			for(String name:signatures.get(type)){
				appendLine(MettelRandomExpressionDefaultPropertiesNames.sortConnectiveFrequencyProperty(type, name) + " = " + SORT_CONNECTIVE_FREQUENCY);
			}
			appendEOL();
			
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortVariableFrequencyProperty(type) + " = " + SORT_VARIABLE_FREQUENCY);
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortVariableDepthProperty(type) + " = " + SORT_VARIABLE_DEPTH);
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortVariablesProperty(type) + " = " + SORT_VARIABLES_TEXT);
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortVariablesSizeProperty(type) + " = " + SORT_VARIABLES_NUMBER);
			appendEOL();
			
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortGenerateProperty(type) + " = " + SORT_GENERATE);
			appendEOL();
			
			appendLine(MettelRandomExpressionDefaultPropertiesNames.sortTopConnectives(type) + " = " + SORT_TOP_CONNECTIVES_TEXT);
			appendEOL();
		}
	}

}
